import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import nodemailer from 'nodemailer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { z } from 'zod';

dotenv.config();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
const dbFile=process.env.DB_FILE?.startsWith('/')?process.env.DB_FILE:path.join(root,process.env.DB_FILE||'data.sqlite');
const uploadDir=path.join(root,'uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(dbFile);
db.pragma('foreign_keys = ON');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'resident',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS complaints(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,photo_path TEXT,priority TEXT NOT NULL DEFAULT 'Medium',status TEXT NOT NULL DEFAULT 'Open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at TEXT,overdue INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS complaint_history(id INTEGER PRIMARY KEY AUTOINCREMENT,complaint_id INTEGER NOT NULL,status TEXT NOT NULL,actor_id INTEGER NOT NULL,note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(complaint_id) REFERENCES complaints(id) ON DELETE CASCADE,FOREIGN KEY(actor_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS notices(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,important INTEGER NOT NULL DEFAULT 0,created_by INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(created_by) REFERENCES users(id));`);
const adminEmail='admin@society.local';
if(!db.prepare('SELECT id FROM users WHERE email=?').get(adminEmail)) db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run('Society Admin',adminEmail,bcrypt.hashSync('Admin@123',10),'admin');
const app=express(); app.use(cors({origin:process.env.CORS_ORIGIN||'http://localhost:5173'})); app.use(express.json()); app.use('/uploads',express.static(uploadDir));
const upload=multer({dest:uploadDir,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\//.test(file.mimetype))});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer ')) throw Error();req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret');next()}catch{return res.status(401).json({error:'Unauthorized'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'})}
async function mail(to,subject,text){if(!process.env.SMTP_HOST){console.log(`[EMAIL MOCK] ${to} | ${subject}\n${text}`);return}const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:false,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transporter.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to,subject,text})}
const registerSchema=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(6)});
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/auth/register',async(req,res)=>{try{const v=registerSchema.parse(req.body);const hash=await bcrypt.hash(v.password,10);const r=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(v.name,v.email.toLowerCase(),hash,'resident');res.status(201).json({id:r.lastInsertRowid})}catch(e){res.status(400).json({error:e.code==='SQLITE_CONSTRAINT_UNIQUE'?'Email already registered':e.message})}});
app.post('/api/auth/login',async(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Invalid credentials'});const token=jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},process.env.JWT_SECRET||'dev-secret',{expiresIn:'1d'});res.json({token,user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
function refreshOverdue(){const days=Number(process.env.OVERDUE_DAYS||7);db.prepare(`UPDATE complaints SET overdue=CASE WHEN status!='Resolved' AND julianday('now')-julianday(created_at)>? THEN 1 ELSE 0 END`).run(days)}
app.get('/api/complaints',auth,(req,res)=>{refreshOverdue();let sql=`SELECT c.*,u.name resident_name,u.email resident_email FROM complaints c JOIN users u ON u.id=c.user_id WHERE 1=1`;const p=[];if(req.user.role==='resident'){sql+=' AND c.user_id=?';p.push(req.user.id)}if(req.query.category){sql+=' AND c.category=?';p.push(req.query.category)}if(req.query.status){sql+=' AND c.status=?';p.push(req.query.status)}if(req.query.date){sql+=' AND date(c.created_at)=date(?)';p.push(req.query.date)}sql+=' ORDER BY c.overdue DESC, CASE c.priority WHEN \'High\' THEN 1 WHEN \'Medium\' THEN 2 ELSE 3 END, c.created_at DESC';const rows=db.prepare(sql).all(...p).map(r=>({...r,overdue:Boolean(r.overdue)}));res.json(rows)});
app.post('/api/complaints',auth,role('resident'),upload.single('photo'),(req,res)=>{const category=String(req.body.category||'').trim(),description=String(req.body.description||'').trim();if(!category||!description)return res.status(400).json({error:'Category and description are required'});const photo=req.file?`/uploads/${path.basename(req.file.path)}`:null;const tx=db.transaction(()=>{const r=db.prepare('INSERT INTO complaints(user_id,category,description,photo_path) VALUES(?,?,?,?)').run(req.user.id,category,description,photo);db.prepare('INSERT INTO complaint_history(complaint_id,status,actor_id,note) VALUES(?,?,?,?)').run(r.lastInsertRowid,'Open',req.user.id,'Complaint created');return r.lastInsertRowid});res.status(201).json({id:tx()})});
app.get('/api/complaints/:id',auth,(req,res)=>{refreshOverdue();const c=db.prepare(`SELECT c.*,u.name resident_name,u.email resident_email FROM complaints c JOIN users u ON u.id=c.user_id WHERE c.id=?`).get(req.params.id);if(!c)return res.status(404).json({error:'Not found'});if(req.user.role==='resident'&&c.user_id!==req.user.id)return res.status(403).json({error:'Forbidden'});c.overdue=Boolean(c.overdue);c.history=db.prepare(`SELECT h.*,u.name actor_name,u.role actor_role FROM complaint_history h JOIN users u ON u.id=h.actor_id WHERE complaint_id=? ORDER BY h.created_at`).all(req.params.id);res.json(c)});
app.patch('/api/complaints/:id',auth,role('admin'),async(req,res)=>{const c=db.prepare('SELECT c.*,u.email FROM complaints c JOIN users u ON u.id=c.user_id WHERE c.id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Not found'});const status=req.body.status??c.status,priority=req.body.priority??c.priority,note=req.body.note||null;if(!['Open','In Progress','Resolved'].includes(status)||!['Low','Medium','High'].includes(priority))return res.status(400).json({error:'Invalid status or priority'});const changed=status!==c.status;db.transaction(()=>{db.prepare(`UPDATE complaints SET status=?,priority=?,resolved_at=CASE WHEN ?='Resolved' THEN CURRENT_TIMESTAMP ELSE NULL END,overdue=CASE WHEN ?='Resolved' THEN 0 ELSE overdue END WHERE id=?`).run(status,priority,status,status,req.params.id);if(changed)db.prepare('INSERT INTO complaint_history(complaint_id,status,actor_id,note) VALUES(?,?,?,?)').run(req.params.id,status,req.user.id,note)} )();if(changed)await mail(c.email,`Complaint #${c.id} status updated`,`Your complaint is now ${status}.${note?` Note: ${note}`:''}`);res.json({ok:true})});
app.get('/api/complaints/:id/history',auth,(req,res)=>{const c=db.prepare('SELECT user_id FROM complaints WHERE id=?').get(req.params.id);if(!c)return res.status(404).json({error:'Not found'});if(req.user.role==='resident'&&c.user_id!==req.user.id)return res.status(403).json({error:'Forbidden'});res.json(db.prepare(`SELECT h.*,u.name actor_name FROM complaint_history h JOIN users u ON u.id=h.actor_id WHERE complaint_id=? ORDER BY h.created_at`).all(req.params.id))});
app.get('/api/notices',auth,(req,res)=>res.json(db.prepare('SELECT n.*,u.name created_by_name FROM notices n JOIN users u ON u.id=n.created_by ORDER BY n.important DESC,n.created_at DESC').all()));
app.post('/api/notices',auth,role('admin'),async(req,res)=>{const title=String(req.body.title||'').trim(),body=String(req.body.body||'').trim(),important=Boolean(req.body.important);if(!title||!body)return res.status(400).json({error:'Title and body are required'});const r=db.prepare('INSERT INTO notices(title,body,important,created_by) VALUES(?,?,?,?)').run(title,body,important?1:0,req.user.id);if(important){for(const u of db.prepare("SELECT email FROM users WHERE role='resident'").all()) await mail(u.email,`Important notice: ${title}`,body)}res.status(201).json({id:r.lastInsertRowid})});
app.get('/api/dashboard',auth,role('admin'),(req,res)=>{refreshOverdue();const byStatus=db.prepare('SELECT status,COUNT(*) count FROM complaints GROUP BY status').all();const byCategory=db.prepare('SELECT category,COUNT(*) count FROM complaints GROUP BY category ORDER BY count DESC').all();const overdue=db.prepare('SELECT COUNT(*) count FROM complaints WHERE overdue=1').get().count;res.json({byStatus,byCategory,overdue})});
app.listen(Number(process.env.PORT||4000),()=>console.log(`API running on http://localhost:${process.env.PORT||4000}`));
